config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
      confirmation: "confirmations"
  }
  resources :posts do
    resources :comments
  end
  #get '/posts', to: 'posts#index', as: :posts
  #get '/posts/new', to: 'posts#new', as: :new_post
  #get '/posts/:id', to: 'posts#show', as: :post
  #post '/posts', to: 'posts#create'
  #get '/posts/:id/edit', to: 'posts#edit', as: :edit_post
  #patch '/posts/:id', to: 'posts#update'


  get '/categories/:category_handle/posts', to: 'posts#index', as: :category_posts

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify


  def self.find_by_handle(handle)
    find_by(handle: handle)
  end

  def self.find_by_handle!(handle)
    find_by_handle(handle) || raise(ActiveRecord::RecordNotFound)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  has_many :comments, dependent: :destroy
  scope :ordered, -> { order(id: :desc)}
  scope :with_categories, -> {includes(:category)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_categories

  private

  def set_categories
    @categories = Category.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username,:comment_text)
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationController < Devise::ConfirmationsController

  private

  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    redirect_to :posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]

  def index
    if params[:category_handle]
      @category = Category.find_by_handle!(params[:category_handle])
      @posts = @category.posts.ordered.with_categories
    end
    @posts ||= Post.ordered.with_categories
    load_categories()
  end

  def show
    load_post()
  end

  def new
    @post = Post.new
    load_categories
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to @post
  end

  def edit
    load_post()
    load_categories()
  end

  def update
    load_post()
    @post.update(post_params)
    redirect_to @post
  end

  def destroy
    load_post()
    @post.destroy
    redirect_to :posts
  end

  private

  def post_params
    params.require(:post).permit(:title,:text, :category_id)
  end

  def load_post
    @post = Post.find(params[:id])
  end

  def load_categories
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'%>
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>

    <nav class="navbar fixed-top navbar-expand-sm  scrolling-navbar">
      <%= link_to 'Football blog', posts_path, class:"navbar-brand" %>
      <ul class="navbar-nav mr-auto">
        <!-- Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            News
          </a>
          <div class="dropdown-menu">
            <% @categories.each do |cat| %>
              <%= link_to cat.name, category_posts_path(category_handle: cat.handle), class:"dropdown-item"%>
            <%end %>
          </div>
        </li>
      </ul>
        <ul class="navbar-nav">
        <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Add new post", new_post_path, class: "nav-link" %>
            </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path,
                        method: :delete, class: "nav-link" %>
          </li>
        <%else %>
          <li class="nav-item mr-auto">
            <%= link_to "Log in", new_user_session_path,
                        class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path,
                        class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </header>
<div class="container main">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do|name,message| %>
        <div class="alert">
          <%= message %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="container" style="  margin-bottom: 100px;">
  <%= yield %>
</div>
  <footer class="fixed-bottom">
    <div class="socials">
      <a target="_blank" href="https://www.facebook.com/vyartim" class="fa fa-facebook"></a>
      <a target="_blank" href="https://twitter.com/JustZendol" class="fa fa-twitter"></a>
      <a target="_blank" href="https://www.instagram.com/ya.vitalb/" class="fa fa-instagram"></a>
      <a target="_blank" href="https://www.youtube.com/channel/UCtdYaH9ueNPggEA4L7s96zA?view_as=subscriber" class="fa fa-youtube"></a>
    </div>
  </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field(:title, {:class =>'form-control'}) %>
  </div>

  <div class="form-group">
    <%= f.label :category_id %><br>
    <%= f.select(:category_id, Category.all.map {|c| [c.name,c.id]}) %>
  </div>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area(:text, {:class =>'form-control'}) %>
  </div>


<%= f.submit({:class => 'btn btn-success'})%>
<% end %>

app/views/posts/_post.html.erb
<div class="posts.container">
  <% @posts.each do |post| %>
    <div>
      <%= link_to post do %>
        <h3><%= post.title %></h3>
      <% end %>
      <p><%= post.category.name %></p>
      <p><%= post.created_at(format: :short) %></p>
      <p><%= post.text %></p>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit post <%= @post.title %></h1>
<%= render partial: 'form' %>

app/views/posts/index.html.erb
<h1>
  <%= @category&.name || 'All'%> posts
</h1>

<% if @category %>
  <%= link_to "All posts", posts_path %>
<% end %>
  <div class="posts.container ">
    <% @posts.each do |post| %>
      <div class="posts truncateLongTexts">
        <%= link_to post.category.name, category_posts_path(category_handle: post.category.handle)%>
        / <%= post.created_at.strftime("%H:%M %d.%m.%Y")%></p>
        <hr>
        <%= link_to post do %>
          <h3 class="imp"><%= post.title %></h3>
        <% end %>
        <p><%= post.text %></p>

      </div>
    <% end %>
  </div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render partial: 'form' %>

app/views/posts/show.html.erb
<div class="posts">
  <%= link_to @post.category.name, category_posts_path(category_handle: @post.category.handle)%>
  / <%= @post.created_at.strftime("%H:%M %d.%m.%Y")%></p>
  <hr>
  <h3 class="imp"><%= @post.title %></h3>
  <p><%= @post.text %></p>

</div>


<div class="edit-delete.container">
  <%= link_to 'Edit', edit_post_path(@post.id), class:"btn btn-danger"%>

  <%=
    link_to 'Delete', post_path(@post.id), method: :delete,
            data: {confirm: "Are you sure?"}, remote:true, class:"btn btn-danger"
  %>
</div>
<div class="link-container" style="margin-top: 20px">
  <%= link_to 'Back to posts', posts_path, class:"btn btn-danger" %>
</div>
<h2>All comments</h2>
<% @post.comments.each  do |comment| %>
  <div class="alert alert-light">
    <p><strong><%= comment.username %></strong>:
      <%= comment.comment_text %></p>
  </div>
<% end %>
<h2>Comments</h2>
<%= form_for([@post, @post.comments.build]) do |post|  %>
  <p>
    Name<br>
    <%=  post.text_field(:username, {:class=>'form-control'}) %>
  </p>
  <p>
    Text<br>
    <%=  post.text_area(:comment_text, {:class=>'form-control'}) %>
  </p>
  <p>
    <%= post.submit("Add comment",{:class => 'btn btn-success'}) %>
  </p>
<%end %>